// Draws the printable Portrait — the Terminal's `/whoami` picture, as glyphs —
// from `public/miyamura.png` and writes it to `components/terminal/portrait.ts`.
//
// A dev-time step rather than a runtime one: the Terminal prints characters, so
// the picture is committed as the characters it prints, and a build needs no
// canvas and no image decoding. Run `npm run portrait` after changing the image.
//
// `sharp` is not a dependency of the site; it is here because Next and the glTF
// tooling already install it for a dev run. `npm i -D sharp` if it is missing.
import { writeFileSync } from "node:fs"
import sharp from "sharp"

/** The image, and the cell the grid is drawn on: a monospace glyph is 0.6 as
 * wide as it is tall, so a square picture is 0.6 times as many rows as columns
 * — and it is printed at `leading-none`, where that ratio holds. */
const SOURCE = "public/miyamura.png"
const OUTPUT = "components/terminal/portrait.ts"
const COLUMNS = 80
const ROWS = Math.round(COLUMNS * 0.6)

/** Light to dark. A space is paper: the Terminal's background shows through. */
const RAMP = " .:-=+*#%@"

/** Bayer 8x8: the ordered dither that carries the midtones a 9-glyph ramp
 * cannot. Without it a face is either ink or paper, and the shading that makes
 * it a face is the first thing lost. */
const BAYER = [
  [0, 32, 8, 40, 2, 34, 10, 42],
  [48, 16, 56, 24, 50, 18, 58, 26],
  [12, 44, 4, 36, 14, 46, 6, 38],
  [60, 28, 52, 20, 62, 30, 54, 22],
  [3, 35, 11, 43, 1, 33, 9, 41],
  [51, 19, 59, 27, 49, 17, 57, 25],
  [15, 47, 7, 39, 13, 45, 5, 37],
  [63, 31, 55, 23, 61, 29, 53, 21],
]

const { data } = await sharp(SOURCE)
  // The image's own background is light, and the Terminal's is dark: flattening
  // onto white makes transparency paper, which is what a space already means.
  .flatten({ background: "#ffffff" })
  .greyscale()
  .resize(COLUMNS, ROWS, { kernel: "lanczos3", fit: "fill" })
  .raw()
  .toBuffer({ resolveWithObject: true })

const grid = []
for (let row = 0; row < ROWS; row++) {
  let line = ""
  for (let column = 0; column < COLUMNS; column++) {
    // Dark is ink. Dense glyphs are what prints brightest, so the picture's
    // dark cells are the drawn ones and its light background is paper — the
    // polarity that makes a picture out of a photo shot against a light wall.
    // Drawn the other way round, that wall is a solid field of glyphs and the
    // face is what disappears into it.
    const ink = 1 - data[row * COLUMNS + column] / 255
    const dither = (BAYER[row % 8][column % 8] + 0.5) / 64 - 0.5
    const step = Math.round(ink * (RAMP.length - 1) + dither)
    line += RAMP[Math.min(RAMP.length - 1, Math.max(0, step))]
  }
  grid.push(line)
}

const file = `/**
 * The printable Portrait: ${SOURCE} redrawn as a dithered grid of
 * glyphs, so \`/whoami\` shows the owner from the same characters as the rest
 * of the Terminal rather than from a picture.
 *
 * Generated by \`npm run portrait\` — do not edit by hand. ${COLUMNS} x ${ROWS} cells,
 * Bayer-dithered across the ramp \`${RAMP}\` with dark
 * cells drawn dense; the script carries the rest of the reasoning. A space is
 * paper: the grid is printed on the Terminal's own background at
 * \`leading-none\`.
 */
export const PORTRAIT = \`${grid.join("\n")}\`
`

writeFileSync(OUTPUT, file)
console.log(`wrote ${OUTPUT} — ${COLUMNS} x ${ROWS} characters`)
